before:
  hooks:
    - go mod download
archives:
  - id: webhook-go
    format_overrides:
      - goos: windows
        format: zip
builds:
  - id: webhook-go
    ldflags: -s -w -X 'github.com/voxpupuli/webhook-go/cmd.version={{.Version}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
release:
  github:
    owner: voxpupuli
    name: webhook-go
  name_template: "Release v{{.Version}}"
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
