before:
  hooks:
    - go mod download
archives:
  - id: webhook-go
    format_overrides:
      - goos: windows
        format: zip
builds:
  - id: webhook-go
    ldflags: -s -w -X 'github.com/voxpupuli/webhook-go/cmd.version={{.Version}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
nfpms:
    - vendor: Vox Pupuli
      homepage: https://github.com/voxpupuli/webhook-go
      maintainer: Vox Pupuli <voxpupuli@groups.io>
      description: |-
          Puppet Webhook API server written in Go.
          Designed to provide a web api that can receive
          webhooks from VCS services such as GitHub, GitLab, etc
          and execute r10k deployments
      license: Apache 2.0
      formats:
          - deb
          - rpm
      contents:
        - src: build/webhook.yml
          dst: /etc/voxpupuli/webhook.yml
          type: "config|noreplace"
        - src: build/webhook-go.service
          dst: /etc/systemd/system/webhook-go.service
      scripts:
          postinstall: "build/post-install.sh"
          postremove: "build/post-remove.sh"
release:
  github:
    owner: voxpupuli
    name: webhook-go
  name_template: "Release v{{.Version}}"
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
